export type { IEntity, EntityId, INeighborAwareEntity } from './IEntity.ts'
export { EntityState } from './IEntity.ts'
export type { IEntityConfig } from './IEntityConfig.ts'
export type { IEntityCallbacks } from './IEntityCallbacks.ts'
export type { IAggressiveEntityConfig } from './IAggressiveEntityConfig.ts'
export { AggressionMode } from './IAggressiveEntityConfig.ts'
